server:
  port: 9001
  servlet:
    context-path: /api/auth
spring:
  application:
    name: auth

keycloak:
  auth-server-url: http://47.113.227.247:18080
  realm: microservice
  client:
    id: demo-client
    secret: nbNSPDx6bwQ7j5LXQ9eV31cXHfgHmZ6Z
  admin:
    username: admin
    password: admin

