spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

dubbo:
  scan:
    base-packages: com.example
  protocol:
    name: dubbo
    port: -1
server:
  port: 20000
  servlet:
    context-path: /consumer