spring:
  application:
    name: consumer
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        ephemeral: false
dubbo:
  scan:
    base-packages: com.example
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: provider
  registry:
    address: nacos://localhost:8848
server:
  port: 20000
  servlet:
    context-path: /consumer