spring:
  application:
    name: rocketmq-producer
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: node0.com:9876
      bindings:
        output:
          destination: test-consumer-topic
          content-type: application/json
server:
  port: 8082
  servlet:
    context-path: /producer
